/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedTeacherRouteImport } from './routes/_protected/teacher'
import { Route as ProtectedStudentRouteImport } from './routes/_protected/student'
import { Route as ProtectedStaffRouteImport } from './routes/_protected/staff'
import { Route as ProtectedParentRouteImport } from './routes/_protected/parent'
import { Route as ProtectedBranchRouteImport } from './routes/_protected/branch'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedTeacherDashboardRouteImport } from './routes/_protected/teacher/dashboard'
import { Route as ProtectedStudentDashboardRouteImport } from './routes/_protected/student/dashboard'
import { Route as ProtectedStaffDashboardRouteImport } from './routes/_protected/staff/dashboard'
import { Route as ProtectedParentDashboardRouteImport } from './routes/_protected/parent/dashboard'
import { Route as ProtectedBranchDashboardRouteImport } from './routes/_protected/branch/dashboard'
import { Route as ProtectedAdminDashboardRouteImport } from './routes/_protected/admin/dashboard'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTeacherRoute = ProtectedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedStudentRoute = ProtectedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedStaffRoute = ProtectedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedParentRoute = ProtectedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBranchRoute = ProtectedBranchRouteImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedTeacherDashboardRoute =
  ProtectedTeacherDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedTeacherRoute,
  } as any)
const ProtectedStudentDashboardRoute =
  ProtectedStudentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedStudentRoute,
  } as any)
const ProtectedStaffDashboardRoute = ProtectedStaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedStaffRoute,
} as any)
const ProtectedParentDashboardRoute =
  ProtectedParentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedParentRoute,
  } as any)
const ProtectedBranchDashboardRoute =
  ProtectedBranchDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedBranchRoute,
  } as any)
const ProtectedAdminDashboardRoute = ProtectedAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/branch': typeof ProtectedBranchRouteWithChildren
  '/parent': typeof ProtectedParentRouteWithChildren
  '/staff': typeof ProtectedStaffRouteWithChildren
  '/student': typeof ProtectedStudentRouteWithChildren
  '/teacher': typeof ProtectedTeacherRouteWithChildren
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/branch/dashboard': typeof ProtectedBranchDashboardRoute
  '/parent/dashboard': typeof ProtectedParentDashboardRoute
  '/staff/dashboard': typeof ProtectedStaffDashboardRoute
  '/student/dashboard': typeof ProtectedStudentDashboardRoute
  '/teacher/dashboard': typeof ProtectedTeacherDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/branch': typeof ProtectedBranchRouteWithChildren
  '/parent': typeof ProtectedParentRouteWithChildren
  '/staff': typeof ProtectedStaffRouteWithChildren
  '/student': typeof ProtectedStudentRouteWithChildren
  '/teacher': typeof ProtectedTeacherRouteWithChildren
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/branch/dashboard': typeof ProtectedBranchDashboardRoute
  '/parent/dashboard': typeof ProtectedParentDashboardRoute
  '/staff/dashboard': typeof ProtectedStaffDashboardRoute
  '/student/dashboard': typeof ProtectedStudentDashboardRoute
  '/teacher/dashboard': typeof ProtectedTeacherDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/branch': typeof ProtectedBranchRouteWithChildren
  '/_protected/parent': typeof ProtectedParentRouteWithChildren
  '/_protected/staff': typeof ProtectedStaffRouteWithChildren
  '/_protected/student': typeof ProtectedStudentRouteWithChildren
  '/_protected/teacher': typeof ProtectedTeacherRouteWithChildren
  '/_protected/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/_protected/branch/dashboard': typeof ProtectedBranchDashboardRoute
  '/_protected/parent/dashboard': typeof ProtectedParentDashboardRoute
  '/_protected/staff/dashboard': typeof ProtectedStaffDashboardRoute
  '/_protected/student/dashboard': typeof ProtectedStudentDashboardRoute
  '/_protected/teacher/dashboard': typeof ProtectedTeacherDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/branch'
    | '/parent'
    | '/staff'
    | '/student'
    | '/teacher'
    | '/admin/dashboard'
    | '/branch/dashboard'
    | '/parent/dashboard'
    | '/staff/dashboard'
    | '/student/dashboard'
    | '/teacher/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/branch'
    | '/parent'
    | '/staff'
    | '/student'
    | '/teacher'
    | '/admin/dashboard'
    | '/branch/dashboard'
    | '/parent/dashboard'
    | '/staff/dashboard'
    | '/student/dashboard'
    | '/teacher/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_auth/login'
    | '/_protected/admin'
    | '/_protected/branch'
    | '/_protected/parent'
    | '/_protected/staff'
    | '/_protected/student'
    | '/_protected/teacher'
    | '/_protected/admin/dashboard'
    | '/_protected/branch/dashboard'
    | '/_protected/parent/dashboard'
    | '/_protected/staff/dashboard'
    | '/_protected/student/dashboard'
    | '/_protected/teacher/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/teacher': {
      id: '/_protected/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof ProtectedTeacherRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/student': {
      id: '/_protected/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof ProtectedStudentRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/staff': {
      id: '/_protected/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof ProtectedStaffRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/parent': {
      id: '/_protected/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ProtectedParentRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/branch': {
      id: '/_protected/branch'
      path: '/branch'
      fullPath: '/branch'
      preLoaderRoute: typeof ProtectedBranchRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/teacher/dashboard': {
      id: '/_protected/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof ProtectedTeacherDashboardRouteImport
      parentRoute: typeof ProtectedTeacherRoute
    }
    '/_protected/student/dashboard': {
      id: '/_protected/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof ProtectedStudentDashboardRouteImport
      parentRoute: typeof ProtectedStudentRoute
    }
    '/_protected/staff/dashboard': {
      id: '/_protected/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof ProtectedStaffDashboardRouteImport
      parentRoute: typeof ProtectedStaffRoute
    }
    '/_protected/parent/dashboard': {
      id: '/_protected/parent/dashboard'
      path: '/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ProtectedParentDashboardRouteImport
      parentRoute: typeof ProtectedParentRoute
    }
    '/_protected/branch/dashboard': {
      id: '/_protected/branch/dashboard'
      path: '/dashboard'
      fullPath: '/branch/dashboard'
      preLoaderRoute: typeof ProtectedBranchDashboardRouteImport
      parentRoute: typeof ProtectedBranchRoute
    }
    '/_protected/admin/dashboard': {
      id: '/_protected/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof ProtectedAdminDashboardRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedAdminRouteChildren {
  ProtectedAdminDashboardRoute: typeof ProtectedAdminDashboardRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminDashboardRoute: ProtectedAdminDashboardRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedBranchRouteChildren {
  ProtectedBranchDashboardRoute: typeof ProtectedBranchDashboardRoute
}

const ProtectedBranchRouteChildren: ProtectedBranchRouteChildren = {
  ProtectedBranchDashboardRoute: ProtectedBranchDashboardRoute,
}

const ProtectedBranchRouteWithChildren = ProtectedBranchRoute._addFileChildren(
  ProtectedBranchRouteChildren,
)

interface ProtectedParentRouteChildren {
  ProtectedParentDashboardRoute: typeof ProtectedParentDashboardRoute
}

const ProtectedParentRouteChildren: ProtectedParentRouteChildren = {
  ProtectedParentDashboardRoute: ProtectedParentDashboardRoute,
}

const ProtectedParentRouteWithChildren = ProtectedParentRoute._addFileChildren(
  ProtectedParentRouteChildren,
)

interface ProtectedStaffRouteChildren {
  ProtectedStaffDashboardRoute: typeof ProtectedStaffDashboardRoute
}

const ProtectedStaffRouteChildren: ProtectedStaffRouteChildren = {
  ProtectedStaffDashboardRoute: ProtectedStaffDashboardRoute,
}

const ProtectedStaffRouteWithChildren = ProtectedStaffRoute._addFileChildren(
  ProtectedStaffRouteChildren,
)

interface ProtectedStudentRouteChildren {
  ProtectedStudentDashboardRoute: typeof ProtectedStudentDashboardRoute
}

const ProtectedStudentRouteChildren: ProtectedStudentRouteChildren = {
  ProtectedStudentDashboardRoute: ProtectedStudentDashboardRoute,
}

const ProtectedStudentRouteWithChildren =
  ProtectedStudentRoute._addFileChildren(ProtectedStudentRouteChildren)

interface ProtectedTeacherRouteChildren {
  ProtectedTeacherDashboardRoute: typeof ProtectedTeacherDashboardRoute
}

const ProtectedTeacherRouteChildren: ProtectedTeacherRouteChildren = {
  ProtectedTeacherDashboardRoute: ProtectedTeacherDashboardRoute,
}

const ProtectedTeacherRouteWithChildren =
  ProtectedTeacherRoute._addFileChildren(ProtectedTeacherRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedBranchRoute: typeof ProtectedBranchRouteWithChildren
  ProtectedParentRoute: typeof ProtectedParentRouteWithChildren
  ProtectedStaffRoute: typeof ProtectedStaffRouteWithChildren
  ProtectedStudentRoute: typeof ProtectedStudentRouteWithChildren
  ProtectedTeacherRoute: typeof ProtectedTeacherRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedBranchRoute: ProtectedBranchRouteWithChildren,
  ProtectedParentRoute: ProtectedParentRouteWithChildren,
  ProtectedStaffRoute: ProtectedStaffRouteWithChildren,
  ProtectedStudentRoute: ProtectedStudentRouteWithChildren,
  ProtectedTeacherRoute: ProtectedTeacherRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
